dependencies:
- name: redis
  version: 12.8.3-bb.0
  repository: file://external
  condition: redis-ha.enabled
  alias: redis-bb
- name: gluon
  version: "0.1.1"
  repository: "oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon"