{{- $bbtests := .Values.bbtests | default dict -}}
{{- $enabled := (hasKey $bbtests "enabled") -}}
{{- if $enabled }}
{{- if and .Values.networkPolicies.enabled .Values.bbtests.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-helm-test-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      helm-test: enabled
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicies.controlPlaneCidr }}
        # ONLY Block requests to AWS metadata IP
        except:
        - 169.254.169.254/32
{{- end }}
{{- end }}
