{{- if and .Values.networkPolicies.enabled .Values.monitoring.enabled (index .Values "redis-bb" "enabled") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis-monitoring
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis-bb
      app.kubernetes.io/instance: argocd-argocd
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: prometheus 
      namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
    ports:
    - port: 9121
      protocol: TCP
{{- end }}
