{{- if and .Values.istio.enabled (eq .Values.istio.mtls.mode "STRICT") }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: argocd-application-controller-metrics-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
  portLevelMtls:
    "8082":
      mode: PERMISSIVE
{{- end }}
