namespace: argocd

resources:
  - namespace.yaml
  - install.yaml

images:
  # Use our own custom image
  # NOTE: It is up to the "consumer" to provide the necssary ImagePullSecrets to pull this
  - name: argoproj/argocd:v1.5.5
    newName: registry.dsop.io/platform-one/apps/argocd/argocd-repo-server
    newTag: v1.5.5-0.1.2
