{{- if and (.Values.awsCredentials.awsAccessKeyId) (.Values.awsCredentials.awsSecretAccessKey) (.Values.awsCredentials.awsDefaultRegion) }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-iam-secret
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-iam-secret
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: {{ .Values.server.name }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.awsCredentials.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsCredentials.awsSecretAccessKey | b64enc }}  
  AWS_DEFAULT_REGION: {{ .Values.awsCredentials.awsDefaultRegion | b64enc }}  
{{- end }}
