{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-http-envoy-prom-policy
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        ports: 
        - "15090"
        - "15021"
        - "15020"
{{- end }}
