{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.argocd.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: argocd-authz-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "argo-cd.selectorLabels" (dict "context" . "name" .Values.notifications.name) | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.argocd.namespaces | toYaml | nindent 10 }}
        principals: {{ .Values.istio.hardened.argocd.principals | toYaml | nindent 10 }}
{{- end }}
