{{-  if .Values.server.rbacConfigCreate }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.server.name "name" "rbac-cm") | nindent 4 }}
  {{- if .Values.server.rbacConfigAnnotations }}
  annotations:
  {{- range $key, $value := .Values.server.rbacConfigAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- if or .Values.server.rbacConfig .Values.sso.enabled }}
data:
{{- if .Values.server.rbacConfig }}
{{- toYaml .Values.server.rbacConfig | nindent 4 }}
{{- end }}
{{- if .Values.sso.enabled }}
{{- toYaml .Values.sso.rbac | nindent 4}}
{{- end }}
{{- end }}
{{- end }}
