{{-  if .Values.server.rbacConfigCreate }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.server.name "name" "rbac-cm") | nindent 4 }}
  {{- with .Values.server.rbacConfigAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- if or .Values.server.rbacConfig .Values.sso.enabled }}
data:
{{- with .Values.server.rbacConfig }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if .Values.sso.enabled }}
{{- toYaml .Values.sso.rbac | nindent 4}}
{{- end }}
{{- end }}
{{- end }}
