describe('Basic ArgocD', function() {
  it('Check ArgoCD is accessible', function() {
      cy.visit(Cypress.env('url'))
      cy.contains('Username').type(Cypress.env('user'),{delay: 0})
      cy.get('input[type="password"]').type(Cypress.env('password'),{delay: 0})
      cy.get('button[type="submit"]').click()
      cy.contains('No applications yet')
      cy.get('button[qe-id="applications-list-button-new-app"]').click()
      cy.contains('Application Name').type('guestbook',{delay: 0})
      cy.get('input[qe-id="application-create-field-project"]').type('default',{delay: 0})
      cy.get('input[id="sync-option-CreateNamespace"]').click()
      cy.get('input[qe-id="application-create-field-path"]').type('guestbook',{delay: 0})
      cy.get('input[qe-id="application-create-field-repository-url"]').type('https://github.com/argoproj/argocd-example-apps.git',{delay: 0})
      cy.get('input[qe-id="application-create-field-cluster-url"]').type('https://kubernetes.default.svc',{delay: 0})
      cy.get('input[qeid="application-create-field-namespace"]').type('default',{delay: 0})
      cy.get('button[qe-id="applications-list-button-create"]').click()
      cy.get('a[qe-id="applications-tiles-button-sync"]').click()
      cy.get('button[qe-id="application-sync-panel-button-synchronize"]').click()
      cy.contains('guestbook').click()
      cy.contains('Sync OK')
      cy.contains('Healthy')
      cy.contains('Delete').click()
      cy.get('button[qe-id="argo-popup-ok-button"]').click()
      cy.contains('No applications yet')

  })
})
