{{- if and .Values.usePassword (not .Values.existingSecret) -}}
{{- $secretName := include "redis.fullname" . -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "redis.name" . }}
    chart: {{ template "redis.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{ if $secret }}
{{ with $secret }}
  redis-password: {{ get .data "redis-password" }}
{{ end }}
{{ else }}
  redis-password: {{ include "redis.password" . | b64enc | quote }}
{{- end -}}
{{- end -}}